---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: power-os
# description will be included in the image's metadata
description: Personal Fedora Atomic image with Niri as the primary desktop on a Fedora Kinoite base.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-kinoite
image-version: 44 # latest is also supported if you want new updates ASAP

modules:

  - from-file: modules/prebuilt-assets.yaml
  - from-file: modules/bling.yaml
  - from-file: modules/packages.yaml
  - from-file: modules/direct-downloads.yaml
  - from-file: modules/base-files.yaml
  - from-file: modules/systemd.yaml
  - from-file: modules/polkit-agent.yaml
  # - from-file: modules/kde-cleanup.yaml
  - from-file: modules/fonts.yaml
  - from-file: modules/flatpaks.yaml
  - from-file: modules/chezmoi.yaml
  - from-file: modules/os-release.yaml
  - from-file: modules/signing.yaml
